- id: home
  path: /
  type: page
  is_hidden: true

- id: introduction
  path: /introduction
  type: page

- id: demographics
  path: /demographics
  type: page
  blocks:
      # - id: participation-by-country
      #   type: countries
      - id: salary
        type: vertical-bar
        dataKey: breakdown
        bucketKeys: salary
        showDescription: true
      # - id: salary-per-country
      #   type: countries
      - id: years-of-experience
        dataKey: breakdown
        type: vertical-bar
        bucketKeys: yearsOfExperience
        showDescription: true
      - id: company-size
        type: vertical-bar
        dataKey: breakdown
        bucketKeys: companySize
        showDescription: true
      - id: source
        type: horizontal-bar
        dataKey: breakdown
        showDescription: true
      - id: gender
        type: gender
      - id: job-title
        type: horizontal-bar
        dataKey: breakdown
        showDescription: true
      - id: javascript-proficiency
        type: vertical-bar
        dataKey: breakdown
        bucketKeys: javascriptProficiency
        showDescription: true
      - id: backend-proficiency
        type: vertical-bar
        dataKey: breakdown
        bucketKeys: backendProficiency
        showDescription: true

- id: features
  path: /features
  type: page
  defaultBlockType: feature
  blocks:
      - id: features-radial-cluster-overview
        type: features-radial-cluster-overview
      - id: features-overview
        type: features-overview
  children:
      - id: layout
        path: /layout
        type: features
        data:
            section: layout
        blocks:
            - id: overview
              type: features-section-overview
            - id: usage-ratio
              type: features-usage-ratio
            - css-grid
            - flexbox
            - css-multi-column
            - css-writing-modes
            - css-exclusions
            - id: conclusion
              type: conclusion

      - id: shapes-and-graphics
        path: /shapes-and-graphics
        type: features
        data:
            section: shapes-and-graphics
        blocks:
            - id: overview
              type: features-section-overview
            - id: usage-ratio
              type: features-usage-ratio
            - css-shapes
            - object-fit
            - clip-path
            - css-masks
            - blend-modes
            - css-filter-effects
            - id: conclusion
              type: conclusion

      - id: interactions
        path: /interactions
        type: features
        data:
            section: interactions
        blocks:
            - id: overview
              type: features-section-overview
            - id: usage-ratio
              type: features-usage-ratio
            - css-scroll-snap
            - overscroll-behavior
            - overflow-anchor
            - id: conclusion
              type: conclusion

      - id: typography
        path: /typography
        type: features
        data:
            section: typography
        blocks:
            - id: overview
              type: features-section-overview
            - id: usage-ratio
              type: features-usage-ratio
            - web-fonts-font-face
            - variable-fonts
            - line-breaking-properties
            - font-variant
            - initial-letter
            - id: conclusion
              type: conclusion

      - id: animations-and-transforms
        path: /animations-and-transforms
        type: features
        data:
            section: animations-and-transforms
        blocks:
            - id: overview
              type: features-section-overview
            - id: usage-ratio
              type: features-usage-ratio
            - css-transitions
            - css-transforms
            - css-animations
            - id: conclusion
              type: conclusion

      - id: other-features
        path: /other-features
        type: features
        data:
            section: other-features
        blocks:
            - id: overview
              type: features-section-overview
            - id: usage-ratio
              type: features-usage-ratio
            - css-variables
            - support-queries
            - css-containment
            - will-change
            - calc
            - id: conclusion
              type: conclusion

- id: units-and-selectors
  path: /units-and-selectors
  type: page
  blocks:
      - id: units
        type: horizontal-bar
        dataKey: usage
        showDescription: true
      - id: pseudo-elements
        type: horizontal-bar
        dataKey: usage
        showDescription: true
      - id: combinators
        type: horizontal-bar
        dataKey: usage
        showDescription: true
      - id: tree-document-structure
        type: horizontal-bar
        dataKey: usage
        showDescription: true
      - id: attributes
        type: horizontal-bar
        dataKey: usage
        showDescription: true
      - id: links-urls
        type: horizontal-bar
        dataKey: usage
        showDescription: true
      - id: interaction
        type: horizontal-bar
        dataKey: usage
        showDescription: true
      - id: form-controls
        type: horizontal-bar
        dataKey: usage
        showDescription: true

- id: tools-and-methodology
  path: /tools-and-methodology
  type: page
  defaultBlockType: tool
  blocks:
      - id: tools-overview
        type: tools-overview
  children:
      - id: pre-post-processors
        path: /pre-post-processors
        type: tools
        blocks:
            - id: scaled-ranking-overview
              type: tools-scaled-ranking-section-overview
            - id: overview
              type: tools-section-overview
            - id: usage-ratio
              type: tools-usage-ratio
            - sass
            - less
            - postcss
            - stylus
            - id: other-pre-post-processors
              type: horizontal-bar
              dataKey: others
            - id: conclusion
              type: text

      - id: css-frameworks
        path: /css-frameworks
        type: tools
        blocks:
            - id: scaled-ranking-overview
              type: tools-scaled-ranking-section-overview
            - id: overview
              type: tools-section-overview
            - id: usage-ratio
              type: tools-usage-ratio
            - bootstrap
            - materialize-css
            - ant-design
            - semantic-ui
            - bulma
            - foundation
            - uikit
            - tachyons
            - primer
            - tailwind
            - purecss
            - id: other-css-frameworks
              type: horizontal-bar
              dataKey: others
            - id: conclusion
              type: text

      - id: methodologies
        path: /methodologies
        type: tools
        blocks:
            - id: scaled-ranking-overview
              type: tools-scaled-ranking-section-overview
            - id: overview
              type: tools-section-overview
            - id: usage-ratio
              type: tools-usage-ratio
            - bem
            - atomic-css
            - oocss
            - smacss
            - it-css
            - id: other-methodologies
              type: horizontal-bar
              dataKey: others
            - id: conclusion
              type: text

      - id: css-in-js
        path: /css-in-js
        type: tools
        blocks:
            - id: scaled-ranking-overview
              type: tools-scaled-ranking-section-overview
            - id: overview
              type: tools-section-overview
            - id: usage-ratio
              type: tools-usage-ratio
            - styled-components
            - glamor
            - aphrodite
            - jss
            - styled-jsx
            - radium
            - emotion
            - css-modules
            - id: other-css-in-js
              type: horizontal-bar
              dataKey: others
            - id: conclusion
              type: text

- id: other-tools
  path: /other-tools
  type: page
  blocks:
      - id: text-editors
        type: horizontal-bar
        dataKey: usage
        showDescription: true
      - id: browsers
        type: horizontal-bar
        dataKey: usage
        showDescription: true

- id: environments
  path: /environments
  type: page
  blocks:
      - id: browsers
        type: horizontal-bar
        dataKey: environments
        showDescription: true
      - id: form-factors
        type: horizontal-bar
        dataKey: environments
        showDescription: true
      # - id: print-styles
      #   type: vertical-bar
      #   dataKey: environments
      # - id: email-styles
      #   type: vertical-bar
      #   dataKey: environments

- id: resources
  path: /resources
  type: page
  blocks:
      - id: blogs-magazines
        type: horizontal-bar
        dataKey: resources
        showDescription: true
      - id: sites-courses
        type: horizontal-bar
        dataKey: resources
        showDescription: true
      - id: podcasts
        type: horizontal-bar
        dataKey: resources
        showDescription: true

- id: opinions
  path: /opinions
  type: page
  blocks:
      - id: easy-to-learn
        type: opinion-scale
      - id: evolving-too-slowly
        type: opinion-scale
      - id: utility-classes
        type: opinion-scale
        showDescription: true
      - id: selector-nesting
        type: opinion-scale
        showDescription: true
      - id: programming-language
        type: opinion-scale
      - id: enjoy-css
        type: opinion-scale
      - id: missing-features
        type: horizontal-bar
        dataKey: features

- id: awards
  path: /awards
  type: page
  blocks:
      - id: awards
        type: text

- id: conclusion
  path: /conclusion
  type: page
  blocks:
      - id: conclusion
        type: text

- id: support
  path: /support
  type: page
  is_hidden: true
