###############################################################################
# Additionnal resources to attach to contents
# you can use the following resource types:
# - mdn
# - caniuse
# - github
# - npm
###############################################################################
layout:
    css-grid:
        mdn: /en-US/docs/Web/CSS/CSS_Grid_Layout
        caniuse: css-grid
    flexbox:
        mdn: /en-US/docs/Web/CSS/CSS_Flexible_Box_Layout
        caniuse: flexbox
    css-multi-column:
        mdn: /en-US/docs/Web/CSS/CSS_Columns
        caniuse: multicolumn
    css-writing-modes:
        mdn: /en-US/docs/Web/CSS/CSS_Writing_Modes
        caniuse: css-writing-mode
    css-exclusions:
        caniuse: css-exclusions

shapes-and-graphics:
    css-shapes:
        mdn: /en-US/docs/Web/CSS/CSS_Shapes
        caniuse: css-shapes
    object-fit:
        mdn: /en-US/docs/Web/CSS/object-fit
        caniuse: object-fit
    clip-path:
        mdn: /en-US/docs/Web/CSS/clip-path
        caniuse: css-clip-path
    css-masks:
        mdn: /en-US/docs/Web/CSS/CSS_Masking
        caniuse: css-masks
    blend-modes:
        mdn: /en-US/docs/Web/CSS/blend-mode
        caniuse: css-mixblendmode
    css-filter-effects:
        mdn: /en-US/docs/Web/CSS/filter
        caniuse: css-filters

interactions:
    css-scroll-snap:
        mdn: /en-US/docs/Web/CSS/CSS_Scroll_Snap
        caniuse: css-snappoints
    overscroll-behavior:
        mdn: /en-US/docs/Web/CSS/overscroll-behavior
        caniuse: css-overscroll-behavior
    overflow-anchor:
        mdn: /en-US/docs/Web/CSS/overflow-anchor
        caniuse: css-overflow-anchor

typography:
    web-fonts-font-face:
        mdn: /en-US/docs/Web/CSS/@font-face
        caniuse: fontface
    variable-fonts:
        mdn: /en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide
        caniuse: variable-fonts
    line-breaking-properties: {}
    font-variant:
        mdn: /en-US/docs/Web/CSS/font-variant
        caniuse: font-variant-alternates
    initial-letter:
        mdn: /en-US/docs/Web/CSS/initial-letter
        caniuse: css-initial-letter

animations-and-transforms:
    css-transitions:
        mdn: /en-US/docs/Web/CSS/CSS_Transitions
        caniuse: css-transitions
    css-transforms:
        mdn: /en-US/docs/Web/CSS/CSS_Transforms
        caniuse: transforms2d
    css-animations:
        mdn: /en-US/docs/Web/CSS/CSS_Animations
        caniuse: css-animation

other-features:
    css-variables:
        mdn: /en-US/docs/Web/CSS/CSS_Variables
        caniuse: css-variables
    support-queries:
        mdn: /en-US/docs/Web/CSS/@supports
        caniuse: css-supports-api
    css-containment:
        {}
        #mdn:
        #caniuse
    will-change:
        mdn: /en-US/docs/Web/CSS/will-change
        caniuse: will-change
    calc:
        mdn: /en-US/docs/Web/CSS/calc
        caniuse: calc

pre-post-processors:
    sass:
        github: sass/sass
        npm: node-sass
    less:
        github: less/less.js
        npm: less
    postcss:
        github: postcss/postcss
    stylus:
        github: stylus/stylus
        npm: stylus

css-frameworks:
    bootstrap:
        github: twbs/bootstrap
        npm: bootstrap
    materialize-css:
        github: Dogfalo/materialize
        npm: materialize-css
    ant-design:
        github: ant-design/ant-design
        npm: antd
    semantic-ui:
        github: Semantic-Org/Semantic-UI
        npm: semantic-ui
    bulma:
        github: jgthms/bulma
        npm: bulma
    foundation:
        github: zurb/foundation-sites
    uikit:
        github: uikit/uikit
        npm: uikit
    tachyons:
        github: tachyons-css/tachyons
    primer:
        github: primer/css
        npm: '@primer/css'
    tailwind:
        github: tailwindcss/tailwindcss
        npm: tailwindcss
    purecss:
        github: pure-css/pure
        npm: purecss
